[package]
name = "bridge"
version = "0.1.0"
authors = ["Your Name <you@example.com>"]
edition = "2018"

[dependencies]
solana-program = { version = "1.10", features = ["no-entrypoint"] }
bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3

[build]
target = "wasm32-unknown-unknown"