[package]
name = "validator"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
solana-program = { workspace = true }
bincode = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[features]
default = []
no-entrypoint = []
